apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: game-service-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/game`)
      kind: Rule
      services:
        - name: game-service-service
          port: 80
      middlewares:
        - name: strip-game-prefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-game-prefix
spec:
  stripPrefix:
    prefixes:
      - /game
