apiVersion: v1
kind: Service
metadata:
  name: game-service-service
spec:
  type: NodePort
  selector:
    app: game-service
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30000