apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: drawing-service-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/drawing`)
      kind: Rule
      services:
        - name: drawing-service-service
          port: 80
