apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chat-service-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/chat`)
      kind: Rule
      services:
        - name: chat-service-service
          port: 80
      middlewares:
        - name: strip-chat-prefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-chat-prefix
spec:
  stripPrefix:
    prefixes:
      - /chat